FROM eclipse-temurin:17-jdk-jammy AS builder
WORKDIR /workspace
COPY gradlew settings.gradle gradle.properties ./
COPY gradle ./gradle
COPY build.gradle ./
COPY backend/ backend/
RUN chmod +x gradlew
RUN ./gradlew :backend:bootJar --no-daemon

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /workspace/backend/build/libs/lab4-backend.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
