appVersion=1.0.0
mainClass=ru.alesulkins.BackendApplication
backendJarName=lab4-backend.jar

frontendDir=frontend

backendSrcDir=backend/src/main/java

buildClassesDir=build/classes
historyDiffFile=build/history-diff.patch
historyDockerImage=eclipse-temurin:17-jdk-jammy

functionalTestsDir=functional-tests
functionalTestsNodeModulesDir=node_modules
functionalTestsResultsDir=test-results
functionalTestsReportDir=playwright-report
frontendBuildDir=build
frontendNodeCacheDir=node_modules/.cache

composeTestFile=docker-compose.test.yml
functionalTestsService=functional-tests
